src/DripMixPanelIntegration/Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/DripMixPanelIntegration/Web/Models/RuleListViewModel.cs
using System.Collections.Generic;
using Models;

namespace Web.Models
{
    public class RuleListViewModel
    {
        public IList<DripMixPanelRule> Rules { get; set; }
    }
}

src/DripMixPanelIntegration/Web/Controllers/API/DripEventsApiController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
using Microsoft.Extensions.Logging;
using Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Services;

namespace Web.Controllers.API
{
    [Route("api/v1/drip/events")]
    [ApiController]
    public class DripEventsApiController : ControllerBase
    {
        private readonly ILogger<DripEventsApiController> _logger;
        private readonly IMixPanelClient _mixPanelClient;
        private readonly IDripMixPanelRuleService _ruleService;

        public DripEventsApiController(ILogger<DripEventsApiController> logger, IMixPanelClient mixPanelClient, IDripMixPanelRuleService ruleService)
        {
            _logger = logger;
            _mixPanelClient = mixPanelClient;
            _ruleService = ruleService;
        }

        [HttpPost, Route("")]
        public async Task<IActionResult> Post([FromBody] JToken body)
        {
            if (body == null)
                return BadRequest("Missing request body.");

            var matchingRules = _ruleService.GetList(body["event"].Value<string>()).ToArray();

            foreach (var rule in matchingRules)
            {
                dynamic properties = BuildMixPanelData(body, rule);

                await _mixPanelClient.Track(new MixPanelEvent()
                {
                    Event = rule.MixPanelEventName,
                    Properties = properties
                });
            }

            return Ok();
        }

        private object BuildMixPanelData(JToken dripEvent, DripMixPanelRule rule)
        {
            var eo = new ExpandoObject();
            var eoColl = (ICollection<KeyValuePair<string, object>>) eo;

            foreach (var fieldMapping in rule.Fields)
            {
                var fieldPaths = fieldMapping.DripFieldPath.Split('.');
                var value = dripEvent;

                foreach (var field in fieldPaths)
                {
                    value = value[field];
                }

                eoColl.Add(new KeyValuePair<string, object>(fieldMapping.MixPanelFieldName, value));
            }

            dynamic eoDynamic = eo;

            return eoDynamic;
        }
    }
}

src/DripMixPanelIntegration/Web/Controllers/API/RulesApiController.cs
using Microsoft.AspNetCore.Mvc;
using Services;

namespace Web.Controllers.API
{
    [Route("api/v1/rules")]
    [ApiController]
    public class RulesApiController : ControllerBase
    {
        private readonly IDripMixPanelRuleService _ruleService;

        public RulesApiController(IDripMixPanelRuleService ruleService)
        {
            _ruleService = ruleService;
        }

        [HttpGet, Route("")]
        public IActionResult GetList()
        {
            var rules = _ruleService.GetList();
            return Ok(rules);
        }
    }
}

src/DripMixPanelIntegration/Web/Controllers/API/TestApiController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers.API
{
    [Route("api/v1/test")]
    [ApiController]
    public class TestApiController : ControllerBase
    {
        [HttpGet, Route((""))]
        public IActionResult Get()
        {
            return Ok(new
            {
                messag = "hello there."
            });
        }
    }
}

src/DripMixPanelIntegration/Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

src/DripMixPanelIntegration/Web/Controllers/RulesController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Rewrite;
using Services;
using Web.Models;

namespace Web.Controllers
{
    public class RulesController : Controller
    {
        private readonly IDripMixPanelRuleService _ruleService;

        public RulesController(IDripMixPanelRuleService ruleService)
        {
            _ruleService = ruleService;
        }

        public IActionResult Index()
        {
            var vm = new RuleListViewModel()
            {
                Rules = _ruleService.GetList().ToList()
            };

            return View(vm);
        }
    }
}

src/DripMixPanelIntegration/Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/DripMixPanelIntegration/Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/DripMixPanelIntegration/Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<section class="jumbotron text-center">
    <div class="container">
        <h1>Purity Drip & Mixpanel Integration</h1>
        <p class="lead text-muted">
            Some description here
        </p>
    </div>
</section>

src/DripMixPanelIntegration/Web/Views/Rules/Index.cshtml
@model Web.Models.RuleListViewModel

<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Drip Event</th>
                <th scope="col">Mixpanel Event</th>
                <th scope="col">Drip Field</th>
                <th scope="col">Mixpanel Field</th>
            </tr>
        </thead>
        <tbody>
        @for (var i = 0; i < Model.Rules.Count; i++)
        {
            var rule = Model.Rules[i];
            var firstRowPrinted = false;

            foreach (var field in rule.Fields)
            {
            <tr>
                <td>@(firstRowPrinted ? "" : i.ToString())</td>
                <td>@(firstRowPrinted ? "" : rule.DripEventName)</td>
                <td>@(firstRowPrinted ? "" : rule.MixPanelEventName)</td>
                <td>@field.DripFieldPath</td>
                <td>@field.MixPanelFieldName</td>
            </tr>

                if (!firstRowPrinted)
                {
                    firstRowPrinted = true;
                }
            }
        }

        </tbody>
    </table>
</div>

src/DripMixPanelIntegration/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Drip & MixPanel Integration</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Rules" asp-action="Index">Rules</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Drip & MixPanel Integration</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>